HTML completo/ercemapi/ercemapi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('students.urls')),
]

HTML completo/ercemapi/students/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.student_list, name='student_list'),
    path('Criar/', views.student_create, name='student_create'),
    path('Editar/<int:pk>', views.student_update, name='student_update'),
    path('Ver/<int:pk>', views.student_read, name='student_read'),
    path('Excluir/<int:pk>', views.student_delete, name='student_delete'),
]

HTML completo/ercemapi/students/models.py
from django.db import models

class Student(models.Model):
    COURSES = (
        ('Ciência da Computação','Ciência da Computação'),
        ('Fisíca','Fisíca'),
        ('Enfermagem','Enfermagem'),
        ('Engenharia Civil','Engenharia Civil'),
        ('Arquitetura','Arquitetura'),
        ('Química','Química'),
    )
    name = models.CharField(max_length=50)
    birth_date = models.DateField()
    city = models.CharField(max_length=30)
    phone = models.IntegerField()
    cpf = models.IntegerField()
    course = models.CharField(max_length=30, choices=COURSES)
    email = models.EmailField()

HTML completo/ercemapi/students/forms.py
from django import forms
from .models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

HTML completo/ercemapi/students/views.py
from django.shortcuts import render, redirect
from .models import Student
from .forms import StudentForm

def student_list(request,template='students/student_list.html'):
    studants = Student.objects.all()
    return render(request,template,{'alunos':studants})
def student_create(request, template='students/student_form.html'):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:        
        form = StudentForm()
    return render(request,template,{'form':form})    
    
def student_read(request, pk, template='students/student_read.html'):
    student = Student.objects.get(pk=pk)
    return render(request,template,{'aluno':student})    

def student_update(request, pk, template='students/student_form.html'):
    student = Student.objects.get(pk = pk)
    if request.method == 'POST':
        form = StudentForm(request.POST,instance=student)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:        
        form = StudentForm(instance=student)
    return render(request,template,{'form':form})

def student_delete(request, pk, template='students/student_delete.html'):
    student = Student.objects.get(pk = pk)
    if request.method == 'POST':
        student.delete()
        return redirect('/')
    else:
        return render(request,template,{'aluno':student})    

HTML completo/ercemapi/students/templates/students/student_delete.html
<!doctype html>
<html lang="pt-br">
    <head>
        <title>Estudante Excluir</title>
    </head>
    <body>
        <form method="post">
        {% csrf_token %}
        Você tem certeza excluir o estudante: {{aluno.name}}?
        <button type="subimit">Confirmar</button>
        <a href="{% url "student_list" %}">Cancelar</a>
        </form>
    </body>
</html>

HTML completo/ercemapi/students/templates/students/student_form.html
<!doctype html>
<html lang="pt-br">
    <head>
    	<!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <title>Formulário Estudante</title>
    </head>
    <body>
    	<div class="container pt-4">
	    <form method="post">
	    	<fieldset>
	    		<legend>Cadastro de estudante</legend>
	    	</fieldset>
	    {% csrf_token %}
	    <!--{{ form }}-->
	    	<div class="form-group row">
	    		<label class="col-lg-2 col-md-2 col-sm-12 col-form-label" for="nome">Nome:</label>
	    		<div class="col-lg-10 col-md-10 col-sm-12">
	    			<input class="form-control" type="text" name="nome" id="id_nome">
	    		</div>
	    	</div>

	    	<div class="form-group row">
	    		<label class="col-lg-2 col-md-2 col-sm-12 col-form-label" for="data">Data de nascimento:</label>
	    		<div class="col-lg-3 col-md-3 col-sm-12">
	    			<input class="form-control" type="date" name="data" id="id_data">
	    		</div>
	    	</div>

	    	<div class="form-group row">
	    		<label class="col-lg-2 col-md-2 col-sm-12 col-form-label" for="cidade">Cidade:</label>
	    		<div class="col-lg-10 col-md-10 col-sm-12">
	    			<input class="form-control" type="text" name="cidade" id="id_cidade">
	    		</div>
	    	</div>

	    	<div class="form-group row">
	    		<label class="col-lg-2 col-md-2 col-sm-12 col-form-label" for="email">Email:</label>
	    		<div class="col-lg-10 col-md-10 col-sm-12">
	    			<input class="form-control" type="email" name="email" id="id_email">
	    		</div>
	    	</div>

	    	<div class="form-group row">
	    		<label class="col-lg-2 col-md-2 col-sm-12 col-form-label" for="cpf">CPF:</label>
	    		<div class="col-lg-4 col-md-4 col-sm-12">
	    			<input class="form-control" type="text" name="cpf" id="id_cpf">
	    		</div>
	    	</div>

	    	<div class="form-group row">
	    		<label class="col-lg-2 col-md-2 col-sm-12 col-form-label" for="telefone">Telefone:</label>
	    		<div class="col-lg-4 col-md-4 col-sm-12">
	    			<input class="form-control" type="text" name="telefone" id="id_telefone">
	    		</div>
	    	</div>

	    	<div class="form-group row">
	    		<label class="col-lg-2 col-md-2 col-sm-12 col-form-label" for="curso">Curso:</label>
	    		<div class="col-lg-4 col-md-4 col-sm-12">
	    			<select class="form-control">
	    				<option>--------</option>
	    			</select>
	    		</div>
	    	</div>
	    	<div class="text-right">
	    <button type="submit" class="btn btn-primary">Salvar</button>
	    <a href="{% url "student_list" %}" class="btn btn-success">Cancelar</a>
	    	</div>
	    </form>
	    </div>
    </body>
</html>

HTML completo/ercemapi/students/templates/students/student_list.html
<!doctype html>
<html lang="pt-br">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <title>Estudantes</title>
    </head>
    <body>
        <div class="container">
        	<div class="pt-4">
        		<legend>Listagem de estudantes</legend>
        	</div>
        <table class="table">
            <thead>
                <tr class="d-flex">
                    <th class="col-lg-2 col-md-2 col-sm-2">ID</th>
                    <th class="col-lg-4 col-md-4 col-sm-4">Nome</th>
                    <th class="col-lg-3 col-md-3 col-sm-3">Curso</th>
                    <th class="col-lg-3 col-md-3 col-sm-3">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for aluno in alunos %}
                <tr class="d-flex">
                    <td class="col-lg-2 col-md-2 col-sm-2">{{aluno.pk}}</td>
                    <td  class="col-lg-4 col-md-4 col-sm-4">{{aluno.name}}</td>
                    <td class="col-lg-3 col-md-3 col-sm-3">{{aluno.course}}</td>
                    <td class="col-lg-3 col-md-3 col-sm-3">
                        <a href="{% url "student_read" aluno.pk %}" class="btn btn-primary" data-toggle="modal" data-target="#dadosestudante">Ver</a>
                        <!-- Modal visualizar dados -->
						<div class="modal fade" id="dadosestudante" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
						  <div class="modal-dialog">
						    <div class="modal-content">
						      <div class="modal-header">
						        <h5 class="modal-title" id="exampleModalLabel">Dados do estudante</h5>
						        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						          <span aria-hidden="true">&times;</span>
						        </button>
						      </div>
						      <div class="modal-body">
								<p>Nome: {{aluno.name}}<br>
							    Data de nascimento:{{aluno.birth_date}}<br>
							    Cidade:{{aluno.city}}<br>
							    Email:{{aluno.email}}<br>
							    CPF:{{aluno.cpf}}<br>
							    Telefone:{{aluno.phone}}<br>
							    Curso:{{aluno.course}}</p>
						      </div>
						      <div class="modal-footer">
						        <a href="{% url "student_list" %}" class="btn btn-success">Voltar</a>
						      </div>
						    </div>
						  </div>
						</div>
                        <a href="{% url "student_update" aluno.pk %}" class="btn btn-warning">Editar</a>
                        <a href="{% url "student_delete" aluno.pk %}"class="btn btn-danger" data-toggle="modal" data-target="#excluirestudante">Excluir</a>
                            <!-- Modal excluir cadastro -->
							<div class="modal fade" id="excluirestudante" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
							  <div class="modal-dialog">
							    <div class="modal-content">
							      <div class="modal-header">
							        <h5 class="modal-title" id="exampleModalLabel">Dados do estudante</h5>
							        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
							          <span aria-hidden="true">&times;</span>
							        </button>
							      </div>
							      <div class="modal-body">
									<p>Você tem certeza que deseja ecluir: {{aluno.name}} ?</p>
							      </div>
							      <div class="modal-footer">
							        <a href="{% url "student_list" %}" class="btn btn-success">Cancelar</a>
							        <button type="submit" class="btn btn-primary">Confirmar</button>
							      </div>
							    </div>
							  </div>
							</div>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td>Sem resultados<td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="text-right">
        	<a href="{% url "student_create" %}" class="btn btn-success">Novo</a>
        </div>
    </div>
    

	
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

HTML completo/ercemapi/students/templates/students/student_read.html
<!doctype html>
<html lang="pt-br">
    <head>
        <title>Estudante Informações</title>
    </head>
    <body>
    {{aluno.name}}
    {{aluno.birth_date}}
    {{aluno.city}}
    {{aluno.email}}
    {{aluno.cpf}}
    {{aluno.phone}}
    {{aluno.course}}
    <a href="{% url "student_list" %}">Voltar</a>
    </body>
</html>