HTML semi-completo/ercemapi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('studants.urls')),
]

HTML semi-completo/studants/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.studant_list, name='studant_list'),
    path('Criar', views.studant_create, name='studant_create'),
    path('Ler/<int:studant_id>', views.studant_read, name='studant_read'),
    path('Editar/<int:studant_id>', views.studant_update, name='studant_update'),
    path('Excluir/<int:studant_id>', views.studant_delete, name='studant_delete'),
]

HTML semi-completo/studants/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class Studant(models.Model):
    COURSES = (
        ('Ciência da Computação', 'Ciência da Computação'),
        ('Física', 'Física'),
        ('Enfermagem', 'Enfermagem'),
        ('Engenharia Civil', 'Engenharia Civil'),
        ('Arquitetura', 'Arquitetura'),
        ('Química', 'Química'),
    )
    name = models.CharField('Nome',max_length=30)
    birth_date = models.DateField('Data  de Nasimento')
    city = models.CharField('Cidade',max_length=50,default="Viçosa do Ceará")
    phone = models.CharField('Telefone',max_length=11)
    cpf = models.CharField('CPF',max_length=11)
    course = models.CharField('Curso',max_length=50, choices=COURSES)
    email = models.EmailField('E-mail')
    
    

HTML semi-completo/studants/forms.py
from django import forms
from .models import Studant
class StudantForm(forms.ModelForm):
    class Meta:
        model = Studant
        fields = '__all__'

        widgets = {
            'birth_date': forms.TextInput(attrs={'type': 'date'}),
            'cpf': forms.TextInput(attrs={'data-mask':"000.000.000-00",'data-mask-selectonfocus':"true"}),
            'phone': forms.TextInput(attrs={'data-mask':"(00) 0 0000-0000",'data-mask-selectonfocus':"true"})
            }
        

HTML semi-completo/studants/views.py
from django.shortcuts import render, redirect
from .models import Studant
from .forms import StudantForm

def studant_list(request, template='studants/studant_list.html'):
    alunos = Studant.objects.all()
    return render(request, template, {'alunos':alunos})

def studant_create(request, template='studants/studant_form.html'):
    if request.method == 'POST':
        form = StudantForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = StudantForm()
    return render(request, template, {'form': form})

def studant_read(request, studant_id, template='studants/studant_read.html'):
    aluno = Studant.objects.get(id=studant_id)
    return render(request, template,{'aluno':aluno})

def studant_update(request, studant_id, template='studants/studant_form.html'):
    aluno = Studant.objects.get(id=studant_id)
    if request.method == 'POST':
        form = StudantForm(request.POST,instance=aluno)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = StudantForm(instance=aluno)
    return render(request, template, {'form': form})

def studant_delete(request, studant_id, template='studants/studant_delete.html'):
    aluno = Studant.objects.get(id=studant_id)
    if request.method == 'POST':
        aluno.delete()
        return redirect('/')
    else:
        return render(request, template,{'aluno':aluno})

HTML semi-completo/studants/templates/studants/studant_delete.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Estudante Exclusão</title>
  </head>
  <body>
    <form method="post">
    {% csrf_token %}
    Você tem certeza que desejar excluir {{ aluno.name }}?
    <button type="submit" class="btn btn-primary">Deletar</button>
    </form>
    <a href="{% url "studant_list" %}" class="btn btn-success">Cancelar</a>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

HTML semi-completo/studants/templates/studants/studant_form.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src={% static "/admin/jQuery/src/jquery.mask.js" %}></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Estudante Formulário</title>
  </head>
  <body>

  {% load crispy_forms_tags %}
    {% block content %}
      <form method="post" id="myForm">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="{% url "studant_list" %}" class="btn btn-success">Cancelar</a>
      </form>
    {% endblock %}
    
    <script>
    jQuery(function($){
      $("#myForm").submit(function() {
        $("#id_cpf").unmask();
        $("#id_phone").unmask();
      });
    });
    </script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </body>
</html>

HTML semi-completo/studants/templates/studants/studant_list.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Estudantes</title>
  </head>
  <body>
    <table class="table">
    <thead>
        <tr>
        <th scope="col">Id</th>
        <th scope="col">Nome</th>
        <th scope="col">Curso</th>
        <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for aluno in alunos %}
            <tr>
            <th scope="row">{{aluno.pk}}</th>
            <td>{{aluno.name}}</td>
            <td>{{aluno.course}}</td>
            <td>
                <a href="{% url "studant_read" aluno.pk %}" class="btn btn-primary">Ver</a>
                <a href="{% url "studant_update" aluno.pk %}" class="btn btn-warning">Editar</a>
                <a href="{% url "studant_delete" aluno.pk %}" class="btn btn-danger">Excluir</a>
            </td>
            </tr>
        {% empty %}
            <tr>
                <td>Sem resultados</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
    <a href="{% url "studant_create" %}" class="btn btn-success">Novo</a>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

HTML semi-completo/studants/templates/studants/studant_read.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Estudante Informações</title>
  </head>
  <body>
    <h1>{{ aluno.name }}</h1>
    <h1>{{ aluno.birth_date|date:"d F Y" }}</h1>
    <h1>{{ aluno.city }}</h1>
    <h1>{{ aluno.email }}</h1>
    <h1>{{ aluno.cpf }}</h1>
    <h1>{{ aluno.phone }}</h1>
    <h1>{{ aluno.course }}</h1>
    <a href="{% url "studant_list" %}" class="btn btn-success">Voltar</a>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>